### PR TITLE
Host option

### PR DESCRIPTION
**Pull request by norkunas**
I'm not familiar with phpspec tests.

### CODE REVIEW

**Comment by dunglas** [comment]
Looks good to me!

Can you:
- add some lines in the doc about that new option
- squash your commits

Thank you for your contribution @norkunas

**Comment by norkunas** [comment]
I'm failing to squash them :/

**Comment by dunglas** [comment]
Did you try git rebase -I HEAD~10 ?

**Comment by dunglas** [comment]
rebase -i (sorry typing gfrom my phone)

**Comment by norkunas** [comment]
Looks like everything was squashed to 33812b8 (too bad that i don't know how i managed to do that).
Is it good now or i need also to remove the 25d529b?

**Comment by dunglas** [comment]
It's ok. Thank you @norkunas

**Pull request merged**
