### PR TITLE
Added support for excluded routes

### PR DESCRIPTION
**Pull request by leevigraham**
Fixes issues with tests for previous PRs.

### CODE REVIEW

**Comment by leevigraham** [comment]
@dunglas 4af1f4d passed but I rolled back once I re-read the feature.

``` 
  Scenario: We should access excluded page which is behind secure
    Given I send POST request to "/protected-resource/allowed" with invalid csrf header
    Then the response code should be 200
```

What should happen in this case. A CSRF was supplied but it was invalid… however it probably shouldn't have been checked in the first place becuase the url was excluded.

**Comment by leevigraham** [comment]
@dunglas Is this good to merge or do you require something else?

**Comment by leevigraham** [comment]
@dunglas Is there anything holding this PR back?

**Comment by dunglas** [comment]
Thank you very much for this nice addition @leevigraham!

**Comment by qmorek** [comment]
Hi @dunglas,
any ETA when it will be released ?

**Pull request merged**
