### PR TITLE
Fixed Symfony 4.1 deprecations.

### PR DESCRIPTION
**Pull request by leevigraham**
Patch applied in the same format as https://github.com/stof/StofDoctrineExtensionsBundle/commit/ee653c8079ebb7dcf391ed5876357cca41f848b1

### CODE REVIEW

**Comment by SherinBloemendaal** [comment]
Status? My phpunit test returns deprecation notices about those.

**Comment by dunglas** [comment]
Could you give a look to why the tests are red?

**Comment by leevigraham** [comment]
Looks like it's an issue with PHP spec failing with "unexpected method call" on the container builder. I'll try and take a look.

**Comment by leevigraham** [comment]
@dunglas All tests are passing now thanks to the test fixes from @firstred

**Comment by dunglas** [comment]
Thanks @leevigraham

**Comment by firstred** [comment]
Great job everyone! Nice to see that the changes made it into the bundle. I'll close my redundant PRs.

**Comment by leevigraham** [comment]
@dunglas Whats need to create a new release?

**Pull request merged**
