### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by marein**

### CODE REVIEW

**Comment by marein** [comment]
Fixed the test with the following construct. I've expand your if statement. Maybe we should check against the symfony version to make the statement more expressive?

__Current__
```php
if (method_exists('Symfony\Component\DependencyInjection\ContainerBuilder', 'fileExists')) {
    $container
        ->fileExists(Argument::type('string'))
        ->willReturn(true);
} else {
    $container
        ->addResource(Argument::type('Symfony\Component\Config\Resource\FileResource'))
        ->shouldBeCalled();
}
```

__Proposal__
```php
if (class_exists('Symfony\Component\HttpKernel\Kernel') && Kernel::MAJOR_VERSION === 2) {
    $container
        ->addResource(Argument::type('Symfony\Component\Config\Resource\FileResource'))
        ->shouldBeCalled();
} else {
    $container
        ->fileExists(Argument::type('string'))
        ->willReturn(true);
}
```

What do you think?

**Comment by dunglas** [comment]
Hi @marein, thank you very much for handling this! Usually in Symfony we prefer using feature detection than relying on version numbers. I would keep it as is. Do you think that it's ready to be merged?

**Comment by marein** [comment]
Hi, thanks for your explanation. It's ready.

**Comment by dunglas** [comment]
Thanks @marein

**Pull request merged**
